site_name: NEMO Cookbook Tutorial | PROMOTE Sprint 2026
site_url: https://promote-project.github.io/nemo_cookbook_tutorial/

repo_url: https://github.com/promote-project/NEMO_cookbook_tutorial
repo_name: NEMO Cookbook Tutorial
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/icons/promote_logo.png
  favicon: assets/icons/favicon.ico
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - toc.integrate
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - search.suggest

  palette:
    # Dark Mode
    - scheme: default
      primary: white
      accent: blue

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - About: index.md
  - Getting Started: getting_started.md
  - Tutorials:
    - tutorials.md
    - Getting Started with xarray: tutorial_0_getting_started_with_xarray.ipynb
    - Getting Started with NEMO Cookbook: tutorial_1_getting_started_with_nemo_cookbook.ipynb
    - Analysing UKESM1-2-LL with NEMO Cookbook: example_analysing_UKESM1-2-LL_with_nemo_cookbook.ipynb
    - Analysing CANARI-LE with NEMO Cookbook: example_analysing_CANARI_LE_with_nemo_cookbook.ipynb
  - Resources: resources.md

plugins:
  - search
  - glightbox
  - mkdocs-jupyter:
      include_source: True

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/promote-project/NEMO_cookbook_tutorial
      name: GitHub

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js